version: '3.1'
services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.106.0
    volumes:
      - ./docker/otelcol/config.yaml:/etc/otel/config.yaml
    ports:
      - "4317"
      - "4318"
    command:
      - "--config=/etc/otel/config.yaml"
  nginx:
    build: docker/nginx
    ports:
        - "8081:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=dev,service.version=0.0.1
    depends_on:
      - otelcol
